resources:
  - name: code
    type: git
    source:
      uri: https://github.com/kalidhasan45/Astor.git
      branch: master
jobs:
  - name: build
    plan:
    - aggregate:
      - get: code
        trigger: true
    - task: compile
      privileged: true
      file: Pipeline/compile.yml